name: Build and Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Python dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Log in to Google Container Registry
      uses: docker/login-action@v1
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: code/GenAIEmailProcessingApp
        push: true
        tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/genai-email-processing-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Cache Google Cloud SDK
      uses: actions/cache@v4
      with:
        path: ~/google-cloud-sdk
        key: ${{ runner.os }}-gcloud-${{ hashFiles('**/gcloud-config') }}
        restore-keys: |
          ${{ runner.os }}-gcloud-

    - name: Install Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy genai-email-processing-app \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/genai-email-processing-app:latest \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated
